### ISSUE TITLE
typings for wp-api.js

### ISSUE THREAD

**Issue by MurhafSousli** [WP-API/client-js#100]
I have an angular2 app with (WP backend), I want to integrate `client-js` in my components files, I got it working temporarily like this: 
```
export class AppCmp {
  constructor(){
    var wp = window['wp'];
    var postsCollection = new wp.api.collections.Posts();
    postsCollection.fetch( { data: { per_page: 25 } } );
    console.log(postsCollection);
}
```
but It would be great to have type definition for it.
```
import * as WP from './../../assets/wp-api';  //error: can't find module.
```

Thanks.

**Comment by delphinus35** [comment]
`client-js` is not a *module* and has no typings in itself or DefinitelyTyped. So typings should be prepared by other way. I'm also developing app with TypeScript (not Angular2), and have researched about this.

1. There is typings already [here][repo1] and [here][repo2]. But this is too old to use with latest `Backbone.js` typings. I update this and created new typings in [here][repo3], but it is imcomplete yet.

[repo1]: https://github.com/hinaloe/wp-rest-api-tsc-declare
[repo2]: https://github.com/hinaloe/wp-api-client-js-declare
[repo3]: https://github.com/delphinus35/client-js/blob/feature/add-type-definition/ts/declare/index.d.ts

2. I also tried to make `client-js` be a *module* that can be *imported* (ES2015 method) or *required* (such as commonjs method) with its own typings.
  - I tried in [this forked repo][repo4], and it seems to work with my case.

  ```json
  // in package.json
  {
    "definition": {
      ...
      "wp-api": "git+https://github.com/delphinus35/client-js.git#feature/add-type-definition",
      ...
    }
  }
  ```

  ```typescript
  import * as wp from 'wp-api';
  // or
  import wp = require('wp-api');

  const posts = new wp.api.collections.Posts;
  ```

[repo4]: https://github.com/delphinus35/client-js/tree/feature/add-type-definition

----

At first, I want use by *2.* method. But it is problematic and I am almost giving up 😓

**Comment by adamsilverstein** [comment]
@MurhafSousli & @delphinus35

Thanks for bringing this up and working on it.

Happy to help out here with testing or any changes you suggest; my knowledge is limited.

**Comment by adamsilverstein** [comment]
The plugin JS code is now merged to WordPress core where this effort may not be needed? In any case I am going to close this ticket out.  @MurhafSousli feel free to fork the plugin if you need this support, or open a ticket in WP core trac if you feel this change would be useful there.

Thanks.
