### ISSUE TITLE
how to modify request to get embedded posts

### ISSUE THREAD

**Issue by MurhafSousli** [WP-API/client-js#104]
Hi, in my typescript project I get the recent posts like this:
```
    collections = window['wp']['api']['collections'];   
    var postsCollection = new this.collections.Posts();
    postsCollection.fetch({
      data: { per_page: this.perPage }
    }).done((posts)=>{
      this.posts = posts;
      this.totalObjects = postsCollection.state.totalObjects;
      this.totalPages = postsCollection.state.totalPages;
    });
```
but I couldn't know how to modify the request since these are the options
```
wp.api.collections.Posts.options
 * author
 * context
 * filter
 * order
 * orderby
 * page
 * per_page
 * search
 * status
```
I would like to know how can I get the posts embedded (with featuredImage, tags and cats), and also how to get the posts from specific type.
Thank you

**Comment by adamsilverstein** [comment]
@MurhafSousli 

For embeds try this:

```js
...
postsCollection.fetch( {
    data: {
         _embed: true,
        per_page: this.perPage
    }
} ).done( posts ) -> ...
```

Hope this helps.

for the second question, what exactly do you mean by a _specific type?_ the options you get are the same ones exposed by the API. Note that with `filter`you can use WP_Query arguments, see http://v2.wp-api.org/reference/posts/

**Comment by MurhafSousli** [comment]
Yes, it worked, I meant for instance I want to get all the posts of type `project` but now I think I understand how it works, thanks a lot.

```
postsCollection.fetch( {
   filter: {
      post_type: 'projects'
   }
})....
```

**Comment by adamsilverstein** [comment]
yep! you got it @MurhafSousli 

If you project is/becomes public, please share its url as I am collecting a list of sites/projects using the library.

Thanks!

**Comment by MurhafSousli** [comment]
:) https://github.com/MurhafSousli/ng2-wordpress-theme

**Comment by adamsilverstein** [comment]
Cool, thanks.
