### ISSUE TITLE
couple of questions about usage

### ISSUE THREAD

**Issue by MurhafSousli** [WP-API/client-js#109]
Hi, first of all thank you for the great job you do in this library, I'm currently using only `Collections` to get everything I need from wordpress, but there are some things I want to confirm.

What I understood till now:

-  **Load** is for wp authentication.
-  **Collections** is used to fetch data from wp.
-  **Models** is used for Create/Update/Delete operations.
-  **Utils** has the utility functions like changing date format.. etc

because I want to get the most out of this great library, I have couple of questions:

1.  for example I get a collection of posts which have undesired date format, and I've noticed that there is a function in `utils.js` converts the date format but couldn't figure out if I can use it.

2. I had to make my own SinglePost class to handle a post response while I think (but I'm not sure) that the library offers one. `wp.api.models.Posts.defaults` is this the class?

3. Can I get a single post using `Models` ? if so please show me how to use

4. Do I have to dispose the service `wp.api.collections` after I finish using it? *before using this library I used to use `Observable` from rxjs 5 and they don't need to be disposed*

you can check how I'm using the library in my service file [here](https://github.com/MurhafSousli/ng2-wordpress-theme/blob/master/angular/src/assets/service-worker.ts)

**Comment by kadamwhite** [comment]
@MurhafSousli I need to turn in for the night but I'll try to review this Monday or Tuesday my time—thanks for the questions! If you haven't heard from me in 3 days feel free to bump this issue.

**Comment by MurhafSousli** [comment]
@kadamwhite I thought he changed his picture lol

**Comment by adamsilverstein** [comment]
Hello @MurhafSousli,

Glad to hear you are using the library.

The main thing this library provides are Models and Collections matching all the _endpoints_ available in the WP-API. 

A Model represents a single item in the API and WordPress, for example a Post.  

A Collection is a group of models, for example a collection of posts.

Util and Load are primarily for internal functions, I don't think you need to use them except to help develop the library.  

You are right that collections are often read only (or can save new models, but not edit them) and models generally support all CRUD methods. You can check what each endpoint does by examining the API  schema, and each Model/Collection also provides information about the available methods in the `methods` property, for example for the Posts collection:

![](http://cl.ly/2L093v0y1f0N/BUC__10up_BUC_2016-03-18_17-20-20.jpg)

Here are some answers to your questions:
1. don't worry about util, that date stuff is for internal helpers
2. Sounds like you may want `parse`: http://backbonejs.org/#Collection-parse
3. make sure you read the docs on the repo or here http://v2.wp-api.org/extending/javascript-client/, here is an example of getting a post once you know its id:
```js
var post = new wp.api.models.Post( { id: 1 } );
var postPromise = post.fetch();
postPromise.done( function( model ) { ...
    do something 
} );
```
4. you shouldn't need to worry about disposing of the service, although I haven't looked at your exact use case

Let me know if you have further questions, good luck. Closing for now, re-open if you have additional questions.

**Comment by MurhafSousli** [comment]
Thank you so much.
