### ISSUE TITLE
Use Uglify to create un-minified, built script?

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/client-js#11]
I left this as a comment on commit [98954d](https://github.com/WP-API/client-js/commit/98954d16679bec9b1839e78e14c6b88ad0c2740f#commitcomment-6296303), but I'm moving it to an issue to keep the discussion visible:

We definitely need a minified and un-minified version of the wp-api script. What we have now uses Concat to assemble all of the script files into one bundle, and then uses Uglify to assemble the same scripts into a minified version.

Earlier today I'd considered opening a PR using concat as well, but it occured to me that it slightly muddies the water: We then have an un-minified file that's composed of scripts assembled from multiple files that don't have source maps, and a minified file with a source map that references the original source files.

Would it make sense to either

1. use UglifyJS to create both the minified and un-minified files, e.g. by passing `mangle: false, compress: false, beautify: true` to a new `"uniminified"` uglify target; or to
2. derive the uglified version of the script from the concatenated one, so that at least there's parity between the line numbers referenced in the minified and unminified versions?

**Comment by adamsilverstein** [comment]
Closing. At some point since this was opened, we added a non minified build via concat I believe. If there is a need to do something different, please open a new pull request with the details.

Thanks!
