### ISSUE TITLE
Dates cannot be passed as ISO-formatted strings

### ISSUE THREAD

**Issue by rmccue** [WP-API/client-js#112]
In TimeStampedMixin, [datetime attributes are assumed to be Date objects](https://github.com/WP-API/client-js/blob/8d0d955307edb475ca6834c893e8257b116d1b02/js/utils.js#L232-L235). This fails if the date passed in is an ISO string.

This needs to check `attributes[ key ] instanceof Date` instead.

**Comment by adamsilverstein** [comment]
@rmccue - I assume this is for creating a new post/object? 

I'm not sure allowing a string date here is a good idea... I think the assumption is that a date object is provided: on the parse side when you retrieve a post, we are taking the returned strings and parsing them to dates. If we allow a string date here, won't you wind up with some posts with string dates and some with Date object dates (retrieved from the api)? 

Can you describe your use case? Is turning your string into dates going to create more work for you?

**Comment by rmccue** [comment]
This seems to be occurring when you create the objects from JSON yourself, i.e. on page load by using `Posts.reset( data )`. In this case, it's raw data from the API, but not gathered through `Post.fetch()`, so it never gets coerced to a Date object.

**Comment by adamsilverstein** [comment]
That seems like a reasonable use case, I will add a check to avoid assuming we always have a date object. It would be nice to have a unit test for this case as well.
