### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by corky7** [WP-API/client-js#113]
Hi!

Thanks for your nice plugin. It looks very promissing. Although it seems that the first example doesn't work - probably I have an issue on my environment?

```
var post = new wp.api.models.Posts( { title: 'This is a test post' } );
post.save();
```

When I run it, it states error 
`Uncaught TypeError: wp.api.models.Posts is not a constructor(…)`

I have properly (I think) setup script for this
` wp_register_script('gb_scriptv2', plugins_url('../js/script_v2.js', __FILE__ ), array ('jquery', 'underscore', 'backbone', 'wp-api')  );`

Could you please let me know what can be wrong.

**Comment by adamsilverstein** [comment]
@corky7 

Thanks for trying the client library. The docs are out of date and the Post model is now at `wp.api.models.Post` (singular instead of plural). I will update the docs!

**Comment by adamsilverstein** [comment]
looks like our docs got out of sync, the docs on the main wp-api docs site show the correct usage: http://v2.wp-api.org/extending/javascript-client/

**Comment by adamsilverstein** [comment]
I have updated the docs here and submitted a pull request to update the main docs site: https://github.com/WP-API/docs-v2/pull/135.

Please let me know if you have any additional issues @corky7

**Comment by corky7** [comment]
Thank you, @adamsilverstein !
