### ISSUE TITLE
Using the client-js library

### ISSUE THREAD

**Issue by corky7** [WP-API/client-js#117]
Hi @adamsilverstein !

Thanks again for your lib and answering the question.

Now everything works fine. My current question can be dumb, but if possible, please answer.

What is
`wp.api.models.User`

in terms of Backbone? Is it already a model? But why I can't instantiate & bind it to view

```
		var WpUser = new wp.api.models.User ({ id: 1});
		WpUser = WpUser.fetch();
		console.log(WpUser);

		var ivanDirectory = new PersonDirectory ({
			el: $("#personDirectoryContainer"),
			model: new WpUser ()
		});
```

Similar code works for the model I have created manually

`		var Person = Backbone.Model.extend({
			defaults: {
				firstName: "Name",
				lastName: "Last Name",
				birthday: "MM-YYYY"
			},
			initialize: function () {
				console.log('Model init OK' + this.get('firstName') + ' ' + this.get('lastName'));
			}
		});
		var IvanDirectory = new PersonDirectory ({
			el: $("#personDirectoryContainer"),
			model: new Person({ 
				firstName: "John",
				birthday: "10-1910"
			}) 
		});`

**Comment by corky7** [comment]
Actually I sorted it out myself. 
In case this would be useful for someone.

I did the following:

```
		var ivanDirectory = new PersonDirectory ({
			el: $("#personDirectoryContainer"),
			model: new wp.api.models.User ({
				id: "1"
			})
		});
```

And yes, the lib's model is the model

**Comment by hyheg** [comment]
@adamsilverstein Can you give an example of extending the models - for example wp.api.models.Post?

**Comment by adamsilverstein** [comment]
@hyheg Sure! I created this codepen to demonstrate what I am talking about. You could add helpers to get or save data, or to preprocess data before/after syncing to the server.

Here is an example: I add a helper function to make getting a posts display data easier. I create a `SpecialPost` object that has a helper function for `getPostData`. I'm using extend here to conveniently mix in my helper, for a more complex app you might attach to the prototype directly.

http://codepen.io/adamsilverstein/pen/oxEqMX?editors=1111

**Comment by hyheg** [comment]
Makes sense. Thanks for the example and the library!

**Comment by adamsilverstein** [comment]
@hyheg You are welcome; if you build something cool, please share it! If you find a bug, please let me know!

**Comment by hyheg** [comment]
@adamsilverstein Sorry to open this again, but I found that using Backbone, I need to apply custom defaults to the model in collection wp.api.collections.Posts. Does client-js allow me to inherit from an extended model (or override its defaults somehow)?
