### ISSUE TITLE
Add support for JSON Web Token (JWT) Authentication 

### ISSUE THREAD

**Issue by adamsilverstein** [WP-API/client-js#118]
JSON Web Tokens are an open, industry standard RFC 7519 method for representing claims securely between two parties. We should support them with or JS client!

**Comment by hyheg** [comment]
Haven't tested this, just FYI: https://github.com/Tmeister/wp-api-jwt-auth

**Comment by adamsilverstein** [comment]
@hyheg thanks for the link, this will be really helpful for the server side of things. still needed here would be adding support or at least docs into the client library.

**Comment by adamsilverstein** [comment]
Closing for now, if you are still interested in working on this @hyheg we can mopve the work to trac (the client has been merged to core).

Thanks!
