### ISSUE TITLE
Extending the models for a collection

### ISSUE THREAD

**Issue by hyheg** [WP-API/client-js#119]
In the README, it says

> You can use [...] endpoints as-is to read, update, create and delete items using standard Backbone methods (fetch, sync, save & destroy for models, sync for collections). You can also extend these objects to make them your own, and build your views on top of them.

I'm working on making a WP-API powered Backbone app - and using the standard wp.api.collections.Posts(), I'd like to extend the collection's model defaults (wp.api.models.Posts.defaults?) and somewhat adhere to the syntax of Backbone at the same time.

Normally, I'd do something like this:

```
var User = Backbone.Model.extend({
	defaults: {
	    name: 'unknown',
	    occupation: 'unknown',
	    age: 0
  }
});

var Users = Backbone.Collection.extend({
	model: User
});

var SpecialCollection = new Users();

SpecialCollection.add({ name: "miles davis"});
SpecialCollection.add({ name: "dizzy gillespie" });
// or using an url prop and .fetch ...
```

Could you suggest how to add to the defaults of the model used in the client-js collection?

In general, I think it would be nice if the documentation provided more examples of integrating this with the Backbone library to fully utilize the power of "client-js".

**Comment by adamsilverstein** [comment]
@hyheg I agree, some better documentation would be helpful, please contribute back there if you are able.

You can extend the collections or models just like the Backbone prototypes:

```js
var MyUser = wp.api.models.User.extend( {
	defaults: {
		name: 'unknown',
		occupation: 'unknown',
		age: 0
	}
} );
var Users = Backbone.Collection.extend({
    model: MyUser
});

var SpecialCollection = new Users();

SpecialCollection.add({ name: "miles davis"});
SpecialCollection.add({ name: "dizzy gillespie" });

```
