### ISSUE TITLE
How to update user meta?

### ISSUE THREAD

**Issue by pdme** [WP-API/client-js#120]
Is it possible to fetch the current user (new wp.api.models.Me()), and embed all user meta, as seems to be the case for posts?

**Comment by pdme** [comment]
If not, how do I go about saving user meta data?

**Comment by pdme** [comment]
Just so I know I'm on the right path (or not). This is how I update user meta now:

```
var userMetaCollection = new wp.api.collections.UsersMeta(null, {parent: parentId});
userMetaCollection.fetch();
userMetaCollection.findWhere({key: 'key'}).set({value: 'value'}).save({parent: parentId});
```

This works, but seems cumbersome if you have many entries to update. Is there a better way?

**Comment by adamsilverstein** [comment]
@pdme You are on the right path! 

Once you have the userMetaCollection fetched, you can update the model data (using set, and findWhere if you need it is fine). You may be able to save your entire collection by extending backbone collection to save, but i haven't tested that; see some sample approaches here: http://stackoverflow.com/questions/6879138/how-to-save-an-entire-collection-in-backbone-js-backbone-sync-or-jquery-ajax -- i'm not sure our endpoints support bulk meta updates so you may wind up having to extend the server side code as well.

Please let me know if you have more questions and report your findings here if you make some progress!

Thanks.

**Comment by adamsilverstein** [comment]
Closing as resolved for now, please reopen if you are still having this issue.
