### ISSUE TITLE
sessionStorage.setItem throws exception in Safari private mode

### ISSUE THREAD

**Issue by rinatkhaziev** [WP-API/client-js#122]
Hi,

The issue is that even though sessionStorage available in private mode, disk writes are prohibited and Safari throws 
```
[Error] QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.
	setItem (wp-api.js:1010)
	success (wp-api.js:1010)
	success (backbone.min.js:1:6581)
	i (jquery.js:2:27455)
	fireWith (jquery.js:2:28215)
	y (jquery.js:4:22843)
	c (jquery.js:4:26991)
```

See https://github.com/WP-API/client-js/blob/master/js/load.js#L59

The solution would be to either try to catch exception or use some sort of fallback (for example, https://github.com/Download/memorystorage)

**Comment by adamsilverstein** [comment]
@rinatkhaziev thanks for opening the issue, I will work on addressing it.
