### ISSUE TITLE
Question about running plugin on a different server than WordPress

### ISSUE THREAD

**Issue by akhanukov** [WP-API/client-js#126]
Awesome plugin/library! Thank you!

I have a node application on a different server from my WordPress instance running WP-API. I hit the endpoints from the application because I set it up before I found this project and see that the JS libraries could have been helpful. However, I'm wondering if I can run this plugin on my MEAN stack server and enqueue it in my child theme functions file from my PHP server. Or does it have to be installed like a plugin in the same folder structure? I'm new to Node, love it, but the melding of both LAMP and MEAN has been really enjoyable but sometimes I get lost in what's possible and what isn't. Thank you for your attention and assistance!

**Comment by kadamwhite** [comment]
@akhanukov Thanks for the question! I'm not sure I fully understand your system and your use-case, can you clarify slightly? The constructs this library provides are broadly useful, but it is primarily intended for use enqueued from within a WordPress context, such as a plugin or theme. Other projects like [this npm package](https://github.com/kadamwhite/wordpress-rest-api) I'm working on are designed explicitly for use within Node contexts, or non-Backbone client-side contexts.

Let us know what your specific needs are and we'll try to help clarify the response. Thanks!

**Comment by adamsilverstein** [comment]
While the client can be used to connect to remote API's it is designed primarily to be run from WordPress and to connect to the WP REST API as kadamwhite describes.

Thanks for the feedback!
