### ISSUE TITLE
Pagination links

### ISSUE THREAD

**Issue by peterigz** [WP-API/client-js#131]
I'm wondering what my options are for generating pagination links when using backbone to fetch data. I'm working on a woocommerce project and have product filters working with rest api nicely, but obviously if you filter the products the number of pages will change so the pagination links on the page have to be updated. Post collection gives you the current page, total pages etc., it would be nice to also have at least the next and prev links in there too.

There is the link response header which has the next and prev links in there, can they be added to the state in the post collection? Most ideal solution would be to generate the same content as pagination_link maybe though a "register_rest_field" style filter but for the collection/model.

Thanks! :+1:

**Comment by adamsilverstein** [comment]
Hey @peterigz - thanks for the request. 

I am cleaning out this repo now that the client is merged to core. Were you able to get the functionality you wanted here? The client only provides models and collections and does not address VIews/display in any way. You should be able to generate pagination links based on the information contained in the collection state...

You will see data points for currentPage, totalObjects and totalPages:

![image](https://cloud.githubusercontent.com/assets/2676022/19686268/5e5bfcba-9a8e-11e6-8987-adf8371ea550.png)

Hope that helps, closing this issue.

**Comment by peterigz** [comment]
Thanks, I've been meaning to look into this (and the other regarding currentPage), but haven't had the chance, but will do soon as it's part of the theme I'm developing so will let you know how I get on. Good to see it merged into core :)
