### ISSUE TITLE
Backbone Model structure differences in fetch and save

### ISSUE THREAD

**Issue by JasonTheAdams** [WP-API/client-js#132]
As I work more and more with the JS client, I find that it's pretty awkward how things like content/title change depending on whether they're being saved versus fetched. The title, for example, is fetched as an object with raw and rendered properties. On the other hand, when saved it's supposed to be a string.

Especially when taking advantage of collection and model events, the structure of the model isn't reliable. I'm changing the title in one area when the title updates in the model. Since the `'change:title'` event triggers both when the model is synced or when `model.set('title')` is called, I end up needing the following:

```
titleChanged: function() {
  var title = this.model.get('title');
  if ( 'string' === typeof title ) {
    this.$el.find('.lv-title').text(title);
  }
},
```

Not the end of the world, but it definitely made me wonder about the importance of consistency in the model structure. Doesn't seem like a particularly reliable model if it changes depending on which way it's headed.

Thoughts?

**Comment by adamsilverstein** [comment]
Hi @JasonTheAdams!

Thanks for the feedback and for using the client. I see you originally opened this ticket on the main plugin repo: https://github.com/WP-API/WP-API/issues/2643 and you may wind up back there :) 

Currently the WP REST API itself returns the title (content as well) as an object, as you described with `rendered` and `raw` data points. The API expects, however, titles as strings. So the main issue you raise is actually with the API itself and not the client js specific handling. You might try asking about why this is so in the slack room, I remember asking myself and can't recall the reason its done that way. Given that scenario, how would you expect the client to behave, should it try to help you by normalize the data sent to events? we do that a little with Dates where the API returns a timestamp and we turn that into a more useful date object (and the reverse when saving).

In regards to your issues with changes on the models, you may be able to work around the issue more cleanly (although your approach is reasonable) by not listening for `change`, instead listening for `sync` events for updates from the server and then triggering and listening for custom events when you change a property internally, eg. `model.trigger( 'title:changed')`.

Hope that helps!

**Comment by JasonTheAdams** [comment]
Hey @adamsilverstein!

Thanks for the feedback. Regarding the events I'm listening for, I'm listening to both `sync` in one place and `title:changed` in another. I'm using `sync` for retrieving the models from the collection, and `title:changed` for when the user changes the title in one place and I want it to be reflected in another.

But yeah, I wondered where this really belonged. I appreciate the `rendered` and `raw` distinction, but it doesn't seem right that a post can't be retrieved and the title updated without changing the structure of the model consequently. In fact, if you were to retrieve a post and immediately update it, it wouldn't work. That just doesn't seem right.

**Comment by BE-Webdesign** [comment]
Yup this definitely probably does belong in the main API discussion.  My bad.

**Comment by JasonTheAdams** [comment]
Moved this back to WP-API.

**Comment by adamsilverstein** [comment]
@JasonTheAdams also worth noting (and I just noticed) that Backbone will trigger a change event after the sync/save if the api returns different data than is sent in.
