### ISSUE TITLE
currentPage should be set to the "paged" filter variable

### ISSUE THREAD

**Issue by peterigz** [WP-API/client-js#133]
If you fetch a post collection and use the "paged" filter variable to get a certain page, then when using .more() it will fetch the same page over and over again because the request['filter'] variable is merged with the $args variable in the rest controller WP_REST_Posts_Controller::get_items therefore overwriting/ignoring the request['page'] value.

So I think that the state.currentPage should be set to "paged" if it exists and then delete the "paged" variable from the filter so .more() then works as you'd expect. I'm doing this manually as a work around and it works fine but maybe this can be considered a bug?

**Comment by adamsilverstein** [comment]
Thanks for raising this issue @peterigz this does indeed look like a bug. Could you work on a fix based on your workaround?

**Comment by adamsilverstein** [comment]
I moved this ticket to trac for further discussion: https://core.trac.wordpress.org/ticket/38484#ticket
