### ISSUE TITLE
AMD Support

### ISSUE THREAD

**Issue by pcfreak30** [WP-API/client-js#135]
Library should be making use of https://github.com/umdjs/umd/blob/master/templates/commonjsStrict.js

It also needs to define backbone as a dependancy

**Comment by adamsilverstein** [comment]
@pcfreak30 Thanks for the feedback and PR, I'll take a look.

This library is currently designed as a WordPress plugin and is part of the https://github.com/WP-API/WP-API plugin. The backbone dependency is taken care of in the wp_enqueue: https://github.com/WP-API/client-js/blob/master/client-js.php#L17

**Comment by pcfreak30** [comment]
@adamsilverstein if thats the case it should not even have a package.json, though I do need it. Im using this in WP, but im making use of browserify. See #136.

**Comment by adamsilverstein** [comment]
`package.json` is used by the grunt build process. lets continue discussion on the pull request; thanks.
