### ISSUE TITLE
Model being created for post type but not collection

### ISSUE THREAD

**Issue by JasonTheAdams** [WP-API/client-js#138]
Hello!

I'm having an odd bug with a post type that's registered the API. The model is showing up in `wp.api.models` but the collection is not. I'm getting an error when trying to extend it and when I look for it in the console it's clearly not there. I've cleared the sessionStorage and everything but the collection just isn't being added.

Any idea what may be causing this?

**Comment by kadamwhite** [comment]
Thanks for opening the issue. is this concerning a post type that is set to show in rest, or are you registering your own rest route?

**Comment by JasonTheAdams** [comment]
Hi @kadamwhite Yup, it's a custom post type that's set to `show_in_rest`. It does show up in the endpoints just fine, as, like I said, does the model. Aside from the collection not being generated, it appears to be working.

**Comment by JasonTheAdams** [comment]
I believe I figured it out, although I'm not sure if this is intentional or a bug.

When I registered the post type I had `show_in_rest` but omitted `rest_base`. According to the [WordPress documentation](https://codex.wordpress.org/Function_Reference/register_post_type) the `rest_base` defaults to the post time. I felt that was fine so I left it out.

So here's where it gets interesting. If I add a `rest_base` _that is different than the default post type_ it shows up in the `collectionRoutes`. It has to be different though.

I'm very curious if this is considered a bug or is counter-intuitively intentional.

**Comment by kadamwhite** [comment]
As [discussed in slack](https://wordpress.slack.com/archives/core-restapi/p1475265957004707) this sounds like a bug, a reduced test case in the form of a simple plugin that creates & registers a post type and a JS script demonstrating the omission would help to replicate & diagnose. Adam S is taking a look at this issue.

**Comment by adamsilverstein** [comment]
Can you provide some sample sample code for your post type setup? I've always set up custom post types with `show_in_rest` and haven't tested using `rest_base`.

**Comment by JasonTheAdams** [comment]
Just made a pull request for this: #139

**Comment by adamsilverstein** [comment]
Closing as resolved, thanks.
