### ISSUE TITLE
How to get Category data for each post in postsCollection

### ISSUE THREAD

**Issue by tenold** [WP-API/client-js#144]
If I do this:

```
var postsCollection = new wp.api.collections.Posts();
postsCollection.fetch();
```

I'm only seeing the category id returned in the attributes object for each post.

Is there a way to include all category data there? Or from that point, when I'm looping over postsCollection, how do I get the category data for each post?

I tried doing this:

```
postsCollection.each( function( post ) {
    post.getCategories().done( function( postCategories ) {
        // ... do something with the categories.
        // The new post has an single Category: Uncategorized
        console.log( postCategories[0].name );
        // response -> "Uncategorized"
    });
});
```

But this is giving me `post.getCategories is not a function`.

Any insight here? Basically I'm just trying to find out how to loop over posts AND include their categories.

**Comment by Neofish22** [comment]
Hi. I'm having a similar issue. I noted that [this closed issue](https://github.com/WP-API/client-js/issues/110) discusses the same problem as @tenold, but asserts that the latest version should work. Iirc the latest version at that time was the current version (2.0-beta15).

My issue is that any of these getSomething() functions that part of Post are not found, when using models from a collection; specifically trying getAuthorUser presently. Newly created models are fine and can pass the model through the constructor to add it. As you would expect, the functions do exist in wp.api.models.Post.prototype.

I'm about 95% certain I am using 2.0-beta15 (e.g. not the version included with WP).

@tenold Whilst waiting for someone knowledgeable to return, I believe you should be able to use a work-around by reconstructing the models in collection, though I am not sure if this is safe or sensible. One may also be able to do some form of prototype trickery (not sure if there is a method to do that).

**Comment by adamsilverstein** [comment]
@tenold @Neofish22 - Thanks for reporting this issue.  @jesseenterprises and I worked on this issue at WCUS contributor day and have a fix in place here:

https://core.trac.wordpress.org/ticket/39070

Can you please give the patch on this ticket a test and verify it resolves the issue you were seeing?

Thanks! 

ps. Development of this client is moving to core, closing this ticket out.

**Comment by Neofish22** [comment]
@adamsilverstein Thanks Adam. I have just updated to 4.7 and applied the patch. The models do now have the proper prototype. :)

**Comment by adamsilverstein** [comment]
Great!  Will likely get this in for a 4.7.1 release. Thanks for testing.

**Comment by Kn4ppster** [comment]
I've pulled the latest build of wp-api.js from master which appears to include this patch however I'm still receiving the 'getCategories is not a function' error.

`wp.api.loadPromise.done(function() {
    var posts_collection = new wp.api.collections.Posts();

    posts_collection.fetch({
        data: {
            per_page: 6
        }
    }).done(function(posts) {
        posts.forEach(function(post) {
            console.log(post);
            post.getCategories().done(function(post_categories) {
                console.log(post_categories);
            });
        });
    });

});`

Maybe I'm doing something wrong. But I'm still receiving this error even after I run the build tools myself.

Although the qunit tests are broken:

> ............>> PhantomJS error:
>>  TypeError: undefined is not an object (evaluating 'theModel.attributes[0].id') 
>>  [ { file: 'http://wordpress/wp-content/plugins/client-js/tests/wp-api.js',
>>     line: 133,
>>     function: '' },
>>   { file: 'http://wordpress/wp-content/plugins/client-js/bower_components/jquery/dist/jquery.js',
>>     line: 3099,
>>     function: 'fire' },
>>   { file: 'http://wordpress/wp-content/plugins/client-js/bower_components/jquery/dist/jquery.js',
>>     line: 3211,
>>     function: 'fireWith' },
>>   { file: 'http://wordpress/wp-content/plugins/client-js/bower_components/jquery/dist/jquery.js',
>>     line: 8264,
>>     function: 'done' },
>>   { file: 'http://wordpress/wp-content/plugins/client-js/bower_components/jquery/dist/jquery.js',
>>     line: 8605,
>>     function: '' } ]

**Comment by adamsilverstein** [comment]
@Kn4ppster 

hmmm, i think the data returned by fetch is the raw model data and not the constructed models. I'll dig into this a bit more - I think you need to iterate over the original collection (`post_collection.each`) - which will now be populated with the fetched models, instead of the returned objects. 

This worked in my testing:

{{{
wp.api.loadPromise.done(function() {
    var posts_collection = new wp.api.collections.Posts();

    posts_collection.fetch({
        data: {
            per_page: 6
        }
    }).done(function(posts) {
        posts_collection.each(function(post) {
            console.log(post);
            post.getCategories().done(function(post_categories) {
                console.log(post_categories);
            });
        });
    });
});
}}}

**Comment by Kn4ppster** [comment]
Ah yes that works, sorry I'm fairly new to Backbone models, I was expecting a collection of model objects.

**Comment by adamsilverstein** [comment]
Right, I checked and the models are set on the collection when they arrive, see http://backbonejs.org/#Collection-fetch. The data returned from the server in the fetch callback is the underlying model data, not the models themselves. if you want the helper functionality, use the model(s) from the collection.
