### ISSUE TITLE
Allow API to use multiple endpoints at the same time

### ISSUE THREAD

**Issue by lucasstark** [WP-API/client-js#145]
If you need to talk to more than one endpoint the way the api is initialized does not make this straight forward.  

It seems like it should be possible, since wp.api.endpoints is a collection of each unique endpoint you might initialize, however,  the collections and models on each endpoint will be overwritten each time you call wp.api.init, so obviously we need a solid way to initialize more than one endpoint at once.   

An example use case would be in a multisite environment you might want to talk to two of the subsites at the same time.  

You'd think you could do something like this rough example:  
```
    var sites = [];
    
    wp.api.init({
        'apiRoot': 'http://example.com/subsite1/wp-json/'
    }).done(function(endpoint){
        sites[ 1 ] = endpoint;
    });

    wp.api.init({
        'apiRoot': 'http://example.com/subsite2/wp-json/'
    }).done(function(endpoint){
        sites[ 2 ] = endpoint;
    });
```

But now sites[1].collections is configured with the URL for the second site.

**Comment by adamsilverstein** [comment]
@lucasstark  Thanks for the bug report and for your patience!

There was a bug in the underlying mechanism that constructed the models and collections that caused the overwriting you were seeing. I pushed a fix in https://github.com/WP-API/client-js/pull/155 and also built the fixed version in the develop branch. In my testing I am now able to connect to two separate APIs and use them separately.

Can you please re-test with the develop branch and see if this resolves the issue you were seeing? I will work on opening a core ticket so we can get this fix in core as well.

Note that the client also keeps track of each remote you initialize in a collection called `wp.api.endpoints`. also, the top level wp.api.models/collections gets a merged data set including all apis you connect to (via extend so order matters).

**Comment by adamsilverstein** [comment]
Opened a track ticket to get this into core: https://core.trac.wordpress.org/ticket/39683#ticket
