### ISSUE TITLE
Comments/Posts is not a constructor 

### ISSUE THREAD

**Issue by CookieMonster70** [WP-API/client-js#156]
Hi,
I don't know what I'm doing wrong?
I'm getting always the following error:
`wp.api.collections.Comments is not a constructor
    at b.$scope.getCollections (calculator25.js:578)
    at fn (eval at compile (angular.js:15152), <anonymous>:4:162)
    at e (angular.js:26673)`

I have also implemented the following lines, but it doesn't even go inside this function.
`wp.api.loadPromise.done( function() {
    //... use the client here
} )`

In functions.php I have added:
`wp_enqueue_script( 'wp-api' );`

On console I can see the following message: It seems that the wp-api works.
n {cid: "c6", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}

Any help appreciated,
Regards,
Dan

**Comment by adamsilverstein** [comment]
@CookieMonster70 Hi, thanks for the question.

It sounds like the client is not completing initialization which would explain the `done` method never getting called. Can you share your code thats failing and also your API schema (or URL if its public). to get the schema, just open site/wp-json and copy the results.

Thanks.

**Comment by CookieMonster70** [comment]
Hi Adam,
I'm getting back the following, when I enter /wp-json but I didn't copy the complete response it's too huge.:{"name":"SomeCompany","description":"","url":"http:\/\/somepage.com","home":"http:\/\/somepage.com\/de","namespaces":["oembed\/1.0","yoast\/v1","wp\/v2"],"auhentication":[],"routes":{"\/":{"namespace":"","methods":["GET"],"endpoints":[{"methods":["GET"],"args":{"context":{"required":false,"default":"view"}}}],"_links":{"self":"http:\/\/somepage.com\/de\/wp-json\/"}},"\/oembed\/1.0":{"namespace":"oembed\/1.0","methods":["GET"],"endpoints":[{"methods":["GET"],"args":{"namespace":{"required":false,"default":"oembed\/1.0"},"context":{"required":false,"default":"view"}}}],"_links":{"self":"http:\/\/somepage.com\/de\/wp-json\/oembed\/1.0"}},"\/oembed\/1.0\/embed":{"namespace":"oembed\/1.0","methods":["GET"],"endpoints":[{"methods":["GET"],"args":{"url":{"required":true},"format":{"required":false,"default":"json"},"maxwidth":{"required":false,"default":600}}}],"_links":{"self":"http:\/\/somepage.com\/de\/wp-json\/oembed\/1.0\/embed"}},"\/yoast\/v1":{"namespace":"yoast\/v1","methods":["GET"],"endpoints":[{"methods":["GET"],"args":{"namespace":{"required":false,"default":"yoast\/v1"},"context":{"required":false,"default":"view"}}}],"_links":{"self":"http:\/\/somepage.com\/de\/wp-json\/yoast\/v1"}},"\/yoast\/v1\/configurator":{"namespace":"yoast\/v1","methods":["GET","POST"],"endpoints":[{"methods":["GET"],"args":[]},{"methods":["POST"],........................

And here the code I was trying to execute, "Just the examples on the page", wich I encapsulated in a function, which is called from a click event.
var postsCollection = new wp.api.collections.Posts();
postsCollection.fetch();or var postsCollection = new wp.api.collections.Comments();
postsCollection.fetch();orwp.api.loadPromise.done( function() {var postsCollection = new wp.api.collections.Comments();
postsCollection.fetch(); //... use the client here} )
RegardsDan
      Von: Adam Silverstein <notifications@github.com>
 An: WP-API/client-js <client-js@noreply.github.com> 
CC: CookieMonster70 <daniele.trovato@yahoo.de>; Mention <mention@noreply.github.com>
 Gesendet: 14:39 Montag, 16.Januar 2017
 Betreff: Re: [WP-API/client-js] Comments/Posts is not a constructor (#156)
   
@CookieMonster70 Hi, thanks for the question.It sounds like the client is not completing initialization which would explain the done method never getting called. Can you share your code thats failing and also your API schema (or URL if its public). to get the schema, just open site/wp-json and copy the results.Thanks.—

**Comment by CookieMonster70** [comment]
Hi Adam,
I'm getting back the following, when I enter /wp-json but I didn't copy the complete response it's too huge.: `{"name":"SomeCompany","description":"","url":"http:\/\/somepage.com","home":"http:\/\/somepage.com\/de","namespaces":["oembed\/1.0","yoast\/v1","wp\/v2"],"auhentication":[],"routes":{"\/":{"namespace":"","methods":["GET"],"endpoints":[{"methods":["GET"],"args":{"context":{"required":false,"default":"view"}}}],"_links":{"self":"http:\/\/somepage.com\/de\/wp-json\/"}},"\/oembed\/1.0":{"namespace":"oembed\/1.0","methods":["GET"],"endpoints":[{"methods":["GET"],"args":{"namespace":{"required":false,"default":"oembed\/1.0"},"context":{"required":false,"default":"view"}}}],"_links":{"self":"http:\/\/somepage.com\/de\/wp-json\/oembed\/1.0"}},"\/oembed\/1.0\/embed":{"namespace":"oembed\/1.0","methods":["GET"],"endpoints":[{"methods":["GET"],"args":{"url":{"required":true},"format":{"required":false,"default":"json"},"maxwidth":{"required":false,"default":600}}}],"_links":{"self":"http:\/\/somepage.com\/de\/wp-json\/oembed\/1.0\/embed"}},"\/yoast\/v1":{"namespace":"yoast\/v1","methods":["GET"],"endpoints":[{"methods":["GET"],"args":{"namespace":{"required":false,"default":"yoast\/v1"},"context":{"required":false,"default":"view"}}}],"_links":{"self":"http:\/\/somepage.com\/de\/wp-json\/yoast\/v1"}},"\/yoast\/v1\/configurator":{"namespace":"yoast\/v1","methods":["GET","POST"],"endpoints":[{"methods":["GET"],"args":[]},{"methods":["POST"],........................`

And here the code I was trying to execute, "Just the examples on the page", wich I encapsulated in a function, which is called from a click event.
`var postsCollection = new wp.api.collections.Posts();
postsCollection.fetch();
or
var postsCollection = new wp.api.collections.Comments();
postsCollection.fetch();
or
wp.api.loadPromise.done( function() {
var postsCollection = new wp.api.collections.Comments();
postsCollection.fetch();
 //... use the client here} )`

Regards
Dan

**Comment by adamsilverstein** [comment]
Hey Dan aka @CookieMonster70:

Are you certain you are loading the wp-api script, you have to add it as a dependency of your script. Can you try inspecting wp.api.collections after the api initializes? you can do this in the chrome console. do you have Comments? 

![](https://cl.ly/2L2W3X2c0L1T/wpdev__Just_another_WordPress_site_2017-01-20_11-00-09.jpg)

**Comment by emilsgulbis** [comment]
There is similar problem for me to. 
Just made new CPT with REST support and can receive posts via URL **http://example.com/wp-json/wp/v2/testimonials** but when trying to use Javascript API client got `wp.api.collections.Testimonials is not a constructor`

Is there any caching for Models and Collections for Backbone models and way to force update on these?

**Comment by adamsilverstein** [comment]
Closing as inactive, please re-open if you are still having this issue.
