### ISSUE TITLE
Custom endpoint while extending wp.api.Models.User

### ISSUE THREAD

**Issue by samvthom16** [WP-API/client-js#165]
How do I fetch items from the custom end point that is extended from WP_REST_Users_Controller in backbone? 

My version string is 'yka/v1/follow' and I have been trying to do this:

var FollowUser = wp.api.models.User.extend({
	
});

But everytime I do fetch, it still fetches from the wp-json/v2/users
var follow_user = new FollowUser({id:1}).fetch();

Could you suggest on how to add the custom end point while extending the wp models? Sorry, I couldn't find any documentation anywhere regarding this.

**Comment by adamsilverstein** [comment]
Do the custom endpoints appear in the schema? do you have `show_in_rest => true` when you set them up? 

Once they appear in schema the client should automatically create the FollowUser model (note: clear sessionstorage or open new window to get a fresh schema parse)

**Comment by samvthom16** [comment]
They do appear in the schema /wp-json. 

How do I create the FollowUser model from that?

**Comment by adamsilverstein** [comment]
Development of the client is continuing in WordPress Trac (https://core.trac.wordpress.org). @samvthom16 if you are still experiencing an issue you think is a bug, please open a ticket there.
