### ISSUE TITLE
Usage outside of wordpress

### ISSUE THREAD

**Issue by brickcap** [WP-API/client-js#166]
Hi,

Is it possible to use this client outside of a wordpress install? Like say from a static page served by nginx? 

Also how is the authentication handled by the library? Is there any way I can check with my server that the requests being made are by an authenticated user? 

Thanks,
Akshat

**Comment by adamsilverstein** [comment]
It is possible, although the library was primarily designed to be loaded from WordPress - its also Backbone based.  Outside of that context, check out https://github.com/WP-API/node-wpapi.

If your request are authenticated, on the server side they will come from the authenticated user. the library support cookie/nonce authentication by default, a plugin is available to provide oauth1 authentication: 

https://github.com/adamsilverstein/wp-api-js-oauth

**Comment by brickcap** [comment]
Thanks Adam! Does this librrary work in a multisite setup?

**Comment by adamsilverstein** [comment]
Yes. And you can connect to multiple endpoints/sites simultaneously since this ticket was committed (should be backported to 4.7.5, will be in 4.8) https://core.trac.wordpress.org/ticket/39683
