### ISSUE TITLE
Best practice to use client-js as a plugin?

### ISSUE THREAD

**Issue by indefinit** [WP-API/client-js#29]
Hello, I'm sort of new to wordpress development (more of a front end js developer), so apologies if this is a very basic question, but I wasn't clear from the readme.  My goal is to build a backbone app that uses WP-API as my interface to a wordpress instance.

I'm trying to use the backbone client-js with WP-API and I'm a little confused about the development workflow.  Is the best practice to install this entire repo as a plugin under:
``` 
wp-content 
    |--> plugins
        | --> client-js.php
```

and then develop from this repo's js directory (using grunt to concat and minify the src)?

or am I supposed to copy json_api_client_js() into my theme's functions.php file and move the build js into the theme's js directory?

Is there a full example I can look at for reference?  Thanks for your help in advance!

**Comment by indefinit** [comment]
After re-reading the README a few times, I think my confusion is around the setup instruction re: Github pages.  What if I don't want to use Github pages?

**Comment by adamsilverstein** [comment]
@indefinit 

Thanks for taking a look at this library.

In regards to your questions, this library is bundled with the WP-API plugin, actively being developed here: https://github.com/WP-API/WP-API. This client-js repo is more more rapid iteration on the client js library.

Ultimately, this library will be included in core. For now, this library is designed as a plugin, when you activate it, its JS overwrites the copy included in the WP-API plugin. 

Please test with the latest version of the plugin in the develop branch: https://github.com/WP-API/client-js/tree/develop

The library provides models and collections for all endpoints exposed by the API schema, its up to you to extend these as you please and build views.

Thanks again, closing this issue for now, housekeeping!
