### ISSUE TITLE
Is it possibile to EDIT / CREATE custom_meta fields using this plugin?

### ISSUE THREAD

**Issue by gino8080** [WP-API/client-js#31]
How to create / update multiple custom_metas ?

i'm using Advanced custom field

**Comment by adamsilverstein** [comment]
@gino8080 

Yes,

you should be able to this by initiating a collection with all of the post meta and then performing a sync.

something like this, you can also pass the models to the collection as the first parameter, or get them from the server.  if you are updating or getting you would need to pass the parent to the collection (as the second parameter { parent: parentid } )

{{
postMetaCollection = new wp.api.collections.PostsMeta();
postMeta1 = new PostMeta( /* meta data including parent = parent id, check endpoint */ );
postMeta2 = new PostMeta( /* meta data including parent = parent id, check endpoint */ );
postMeta3 = new PostMeta( /* meta data including parent = parent id, check endpoint */ );
postMetaCollection.add( postMeta1 );
postMetaCollection.add( postMeta2 );
postMetaCollection.add( postMeta3 );
postMetaCollection.sync();
}}

Let me know if you have any further questions.
