### ISSUE TITLE
Any chance you guys would build in CPT?

### ISSUE THREAD

**Issue by ryuheiyokokawa** [WP-API/client-js#32]
I'm not sure, but it seems the Backbone models and the collections are static and can't be dynamically assigned to custom post types.  Any chance you are working on that? If not, its very easy to just add what we need, but I figured I'd ask.

**Comment by btown69** [comment]
We are resolving that ASAP, Sorry for the inconvenience for now.

**Comment by ryuheiyokokawa** [comment]
@btown69 awesome. It would be nice to be able to just pass arguments to the model initialization process (maybe filters as an array or something too).

**Comment by adamsilverstein** [comment]
@ryuheiyokokawa @btown69 

Thanks for the suggestion! In the latest version of the plugin in the develop branch (https://github.com/WP-API/client-js/tree/develop), we map models and collections for all endpoints exposed by the api schema using discovery. If you add routes, and ensure they are included in the root endpoint, the library should properly set up models and collections.

Please give it a try!
