### ISSUE TITLE
attributes[key].toISOString is not a function

### ISSUE THREAD

**Issue by nathanaelphilip** [WP-API/client-js#41]
```
toJSON: function() {
			var attributes = _.clone( this.attributes );

			// Serialize Date objects back into 8601 strings
			_.each( parseable_dates, function ( key ) {
				if ( key in attributes ) {
					attributes[key] = attributes[key].toISOString();
				}
			});

			return attributes;
		},
```

Line 105 i think. This only happened when I loaded posts in via this call:

```
$allpoems =  wp_safe_remote_get(esc_url_raw( site_url() ).'/wp-json/wp/v2/posts?filter[posts_per_page]=-1&filter[lang]=');
```
```
APP.data.collections.poems.reset(<?= $allpoems['body'] ?>);
```

using this.model.attributes instead of this.model.toJSON() fixed the issue. Just not sure if that will lead to more consequences down the road.

**Comment by adamsilverstein** [comment]
@nathanaelphilip 

Thanks for your feedback.

Is this issue for the WP_API? this repository is for the JavaScript library included with the WP-API. if you have an endpoint issue with the PHP, please open an issue on the main repository: https://github.com/WP-API/WP-API/issues. 

Thanks!

**Comment by nathanaelphilip** [comment]
will do! thanks Adam :)
