### ISSUE TITLE
Setup models and collections dynamically based on the api schema

### ISSUE THREAD

**Issue by adamsilverstein** [WP-API/client-js#53]
At the suggestion of @okofish and after reading the post about the discovery client from @rmccue , I decided to attempt a rewrite of the JavaScript library with this simple goal:  *instead of predefining models and collections, set them up dynamically based on the api schema*.

[This branch](https://github.com/WP-API/client-js/tree/develop) is a work towards that goal. After loading the JS you will see a complete set of working endpoint models and collections:

![Screenshot](http://cl.ly/312z1k202t2M/This_is_nice__Just_another_WordPress_site_2015-12-11_18-27-18.jpg)

Feedback appreciated!

**Comment by danielbachhuber** [comment]
So cool!

> instead of predefining models and collections, set them up dynamically based on the api schema.

Based on the work you've done so far, how do you feel about this conceptually? Is the API schema descriptive enough? Where is it really helpful, and where does it fall short?

**Comment by okofish** [comment]
Looks great! I haven't gotten a chance to test it yet, but the code is very well documented. I particularly like the schema caching system.

**Comment by adamsilverstein** [comment]
@danielbachhuber - glad you like it :) 

 so far, i'm finding almost all of what i need in the schema; 

I am preserving a copy of each route in the corresponding model or collection, and I'm thinking about how to expose all the contained information. I'm currently working on code that adds default attributes to models by traversing the route endpoints and finding/merging args for endpoints that contain a PUT or POST method. 

This yielded great results for root level object I checked like posts, categories, pages, taxonomies, comments: 

![attributes from schema](http://cl.ly/3n1H1Y0U2n2W/This_is_nice__localdev_2015-12-13_11-26-37.jpg)

however it didn't work correctly for 2nd level items i checked, eg PostsMeta, PostsCategories etc. Examining the schema I don't see args for these endpoints. is that omission intentional, is there an open issue or should i submit a PR?

![](http://cl.ly/3D1Q2h1F0l10/wpdev.localhostwp-jsonwpv2_2015-12-13_11-08-22.jpg)

**Comment by adamsilverstein** [comment]
@okofish glad you like it, thanks for the suggestion! testing and any feedback appreciated, 

I added the caching to avoid multiple calls to the schema endpoint, its sessionStorage, so its easy to clear (new tab does it). i'd like to add jsonp support  and the ability to connect with more than one endpoint, so you could pull in data from multiple apis. maybe a model for endpoint, and a collection to contain them. That would open some fun possibilities. 

Pull requests welcome :)

**Comment by danielbachhuber** [comment]
> Examining the schema I don't see args for these endpoints. is that omission intentional, is there an open issue or should i submit a PR?

Not intentional :) Please open an issue, or create a PR if you feel inclined.

**Comment by adamsilverstein** [comment]
In latest version I parse the endpoint GET and build model/collection options:  so Posts collection gets options of 'author, context, filter, order, orderby, page, per_page, search and status'

**Comment by adamsilverstein** [comment]
@danielbachhuber I was using a slightly outdated version of the wp-api and when I upgraded some of the routes had new data. I will try to audit the endpoints to see whats still missing. 

In addition to the POST/PUT endpoints, I am also now parsing the GET endpoints and adding these as model and collection options, setting defaults if defined.

**Comment by danielbachhuber** [comment]
> I will try to audit the endpoints to see whats still missing.

Sounds good.

**Comment by adamsilverstein** [comment]
verified that with this new approach, a CPT added with 	`'show_in_rest' => true` automatically creates matching models and collections for the resulting endpoints.

**Comment by adamsilverstein** [comment]
Merged these changes to master.
