### ISSUE TITLE
Embeds in collections

### ISSUE THREAD

**Issue by colinhowells** [WP-API/client-js#57]
Is it possible to set _embed when using this? I gather that [embeds are on for collections] (https://github.com/WP-API/WP-API/pull/1459), but I'm unclear on what the syntax would be here; not sure if there's something like `var postsCollection = new wp.api.collections.Posts( {}. { embed: 'yup' } );` and embeds seem to be off by default.

**Comment by adamsilverstein** [comment]
@colinhowells 

Thanks for the question. The docs are a little weak here, I will try to improve that.

You should be able to get post _embed data directly from collections:
`
var posts = new wp.api.collections.Posts()
posts.fetch( { data: { _embed: true } } );
`

Here is how this looks in my console, with this parameter passed, the api returns all post meta data:

![](http://cl.ly/3q1w1c0b1B1Q/test__local_dev_2015-12-27_15-07-03.jpg)

**Comment by colinhowells** [comment]
Ahhhhh it was staring me [right in the face] (https://github.com/tlovett1/_s_backbone/blob/master/js/loop.js#L25) [the whole time] (https://github.com/tlovett1/_s_backbone/blob/master/js/loop.js#L182). Thanks, I'm still learning all this.

One question though: while now I can get to, say, `post._embedded.author[0].name` I can't get ahold of  `post._embedded.['https://api.w.org/featuredmedia'][0].media_details.sizes.medium.source_url` due to the URL in there. I've tried it a few ways but I run into errors each time, I know there's something obvious I'm missing ...

**Comment by adamsilverstein** [comment]
@colinhowells:
I am able to get this with
`postsCollection.models[0].attributes._embedded['https://api.w.org/featuredmedia'][0].media_details.sizes.medium.source_url`

What happens when you try that?

![](http://cl.ly/2i0I1Y1W1h2v/test__local_dev_2015-12-27_16-37-34.jpg)

**Comment by colinhowells** [comment]
Turns out I had a dot in there I didn't need. I had `_embedded.['https://api.w.org/featuredmedia']` but what I needed was `_embedded['https://api.w.org/featuredmedia']` I wasn't expecting that, since `_embedded.author[0]` needs that dot. Evidently closing the URL in brackets serves the same function, which I didn't know.

**Comment by adamsilverstein** [comment]
Cool, marking this as resolved :+1:  Thanks for building on this library!

Please share your project with the rest-api team when/if its in a public place!

**Comment by colinhowells** [comment]
Thanks for taking the time to help, I appreciate it!
