### ISSUE TITLE
Pagination Per Page Problem

### ISSUE THREAD

**Issue by rayhooker** [WP-API/client-js#58]
The example of how to set the per_page posts is not correct.  I am actually trying to work with custom post types but tried the example.  Clearly this is not valid Javascript syntax:

var postsCollection = new wp.api.collections.Posts( {}. { per_page: '25' } );

The other question is that I see how to get "more" but can I go back or start at a particular count?

Ray

**Comment by adamsilverstein** [comment]
good point @rayhooker, thats wrong - I will fix that.

The correct code should be:

`var postsCollection = new wp.api.collections.Posts( );
postsCollection.fetch( { data: { per_page: 25 } } );`

Here is a screenshot of me using this in the console:

![pagination](http://cl.ly/2K343d2W1v3w/test__local_dev_2015-12-27_14-54-08.jpg)

Thanks for pointing this documentation error out, can you please test with the above code and see if this resolves your issue?

**Comment by adamsilverstein** [comment]
Corrected the readme.

**Comment by rayhooker** [comment]
That works great. Perfect!!  I am also working out a few more options such as orderby (e.g., "page", "slug" or maybe even ordering by title/ rendered).

I tried for a custom post type:
Projects.fetch({ data: { per_page: 5, orderby: 'slug' }})

That did not work but OTOH, the following does work:
Projects.fetch({ data: { per_page: 5, page: 2}})

Is there something special about orderby that requires a different approach. 

I think page size, page selection, orderby and filter by values to search to search are the most common items for retrieving and displaying posts.

**Comment by adamsilverstein** [comment]
Hey @rayhooker glad that helped.

I will dig into orderby, I haven't tried that yet :) We need to match what the API is expecting in the request. Can you verify you are logged in to WordPress, maybe orderby is private and requires authentication?

You can check the endpoint options for the collection with this, they should match what the API reports in its endpoint data:

`wp.api.collections.Posts.options`

I get:

![](http://cl.ly/1m0L3N0M1b1M/test__local_dev_2015-12-27_16-42-14.jpg)

**Comment by rayhooker** [comment]
Okay so I found the answer:

Projects.fetch({ data: { per_page: 5, filter: { orderby: 'title', order: 'ASC' }}})

You can pass a filter to control the order.  Also you can then select out the per page and the page as well 

Projects.fetch({ data: { per_page: 5, page: 2, filter: { orderby: 'title', order: 'ASC' }}})

This returns the second page of a set of in this case 21 objects with 5 per page and ordere by title ascending order.

**Comment by adamsilverstein** [comment]
@rayhooker 

I was able to get orderby working with 'filter', this changed the order for me, can you try this?

`postsCollection.fetch( {data: { 'filter[orderby]': 'name', 'filter[order]': 'asc', per_page: 5 } } )`

**Comment by rayhooker** [comment]
It looks like both options work.  The only comment is that I don't believe "name" is a valid field for posts so assuming I have already done a new on a collection for the "Project" post type and assigned it to "Project", the following worked for me:

Project.fetch( {data: { 'filter[orderby]': 'title', 'filter[order]': 'dsc', per_page: 5 } } )

**Comment by rayhooker** [comment]
I saw both options that include the notation I posted above. I have not traced the code to see why both work, but they both seem logically equivalent.

**Comment by adamsilverstein** [comment]
Great, glad that worked, closing this issue. Please feel free to open a new issue if you run into any issues. Also, please share your project with the team if its public/sharable. Thanks for trying out the client-js library.

Note: re 'name' vs. 'slug' -- 

In general, WP-API passes these values on to WP_Query, so you can check those docs to see what options are available and how to use them. For order and orderby, see: https://codex.wordpress.org/Class_Reference/WP_Query#Order_.26_Orderby_Parameters

`name` is indeed used instead of `slug` - I have no idea why, but I think you will find it works :)
