### ISSUE TITLE
Routing Not Working

### ISSUE THREAD

**Issue by rayhooker** [WP-API/client-js#59]
I am having a fit trying to get routing to work.  I have a page "projects" that displaying a grid of projects (like portfolio with featured image).  The images have imbedded anchor tags to display the project details in a separate page.  That works with the standard post route, but I don't seem be able to get control and display in the same page.   For example:

var Router = Backbone.Router.extend({  
          "projects/:id/": "project",
          "projects/": "projects",
  		  '*notFound': function() {
  		  	console.log("route not found")
  		  }
  		  //'*notFound': 'notFound'
        }
    });
......
Backbone.history.start({ pushState: true, root: '/wordpress-apidev/'});

I have set breakpoints in the functions defined for each route.  The "projects" route works.  I have tried "projects/:id/", "projects/:id", and "project/:id".  I can always change the imbedded link if Backbone's router can get control but it keeps being passed to the wordpress server for anything but the actual current page served up by Wordpress.

Any clues on how to keep Wordpress from getting control?  Is wordpress registering an event that overrides the Backbone Router/history capability?

Ray

**Comment by adamsilverstein** [comment]
@rayhooker 
You could try matching query vars: something like ?projectid=:id then your url would stay at the root page? Maybe share your code on a github repo and I can take a look.

Good luck! I'm closing this ticket though, this is outside the scope of this library.
