### ISSUE TITLE
wp.api.models.Post( { title: 'This is a test post' } );

### ISSUE THREAD

**Issue by tandoigai** [WP-API/client-js#60]
Please change it a bit in the documentation:

The true is:

<pre><code>wp.api.models.Post( { title: 'This is a test post' } );</code></pre>

while in the documentation, it was

<pre><code>wp.api.models.Posts( { title: 'This is a test post' } );</code></pre>

Letter <strong>s</strong> after Post is redundant.

**Comment by adamsilverstein** [comment]
@tandoigai 

Thanks for the issue report. 

In the current version of the plugin code (install this plugin), the models and collections are built out from the API Schema and you will see that the model names have changes slightly to *exactly match their endpoint equivalents* - 

Therefore, the Post model became `Posts`. If you already have code built around Post, it shouldn't be too hard to add a wrapper or change your naming.

Here are the models as they show up now:

![](http://cl.ly/130T201U0R45/test__local_dev_2016-01-02_10-00-09.jpg)
