### ISSUE TITLE
Adding a New Post Does not Update Fields

### ISSUE THREAD

**Issue by rayhooker** [WP-API/client-js#77]
So I am using the client to retrieve a list of related posts to a given post.  It is actually a project custom post type with a need post type.  I am able to retrieve the needs custom post type.  I created it using a standard admin menu, creating it and publishing it.

The idea is to allow the person editing the parent post type to add to the list.  So I add a new item to the collection.  This updates the view nicely.  I am using Epoxy to bind the attributes to the View.  I have verified that he model is being updated and even marked as "changed".

I am trying to sync it back so updates will be changed and new posts created.  I added a method to the Needs collection:

	wp.sponsorConnect.collections.Needs = wp.api.collections.Posts.extend(
		{
			url: WP_API_Settings.root + 'wp/v2/need',
			model: wp.sponsorConnect.models.Need,
			viewEL: undefined,
			syncCollection: function() {
				//wp.sponsorConnect.Backbone.sync('create',this);

				this.sync('create',this);
			}
		}
	);

The new needs post are saved but two problems:
- None of the updates to either existing models or added models are being saved, even though it looks like they are being posted.
- I also want to mark the new posts as status of "publish".

Does collection sync not work? I can see that the model is still marked as changed. Also how can I use wp-api to set the status to "publish"?

Thanks for any suggestions or tips,

Ray

P.S. - An attempt to get a handle on the models and call .save() fails

"<br /> <b>Fatal error</b>: Cannot use object of type WP_Post as array in <b>/Applications/MAMP/htdocs/wordpress-apidev/wp-content/plugins/sponsor-connect/include/custom_post_types.php</b> on line <b>477</b><br /> "

**Comment by adamsilverstein** [comment]
@rayhooker

Thanks for using the client js library. Collection sync will work, however you may need to help it :)

I may need to look at your code a bit more to help, can you post it or parts of it to a gist or github repo?

when syncing back posts in a collection, you may have to add some additional handling. its helpful to inspect the network console in chrome: can you see where the request went and also inspect the response from the API which should help you figure out why the posts are not saved (what is the error message)?

A few things to note: 
* you must be logged in for post save to work, it seems like you are already if this is an admin feature
* if your new posts have id attributes, Backbone will think they are existing posts and try updating them. you can overwrite the method used in save: model.dave( {}. { type: 'POST' } ) will force a post method
* what is the endpoint you are trying to hit to create the posts? I found when building the `saveCategories` helper that I had to track the 'parent_post' for each category so the save action could include it in the POSTed url (/posts/PARENTID/categories)
* Posts are created in a draft state, I don't think you can change that (although I haven't tried). instead you need to make two requests: once to save/create the post; then once to update the post status.

Not sure about your PHP error, I'll need more code to test/reproduce that.

**Comment by adamsilverstein** [comment]
@rayhooker Are you still having this issue or were you able to resolve it? We recently resolved some issues with saving and changes to the API, can you retest and if this issue still remains, please re-open this issue?

Thanks.
