### ISSUE TITLE
Refactor how categories and tags are managed for posts

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/client-js#80]
We changed the implementation in the API, so the JS client needs to be updated accordingly https://github.com/WP-API/WP-API/issues/2032

**Comment by adamsilverstein** [comment]
Thanks for pointing this out @danielbachhuber - I will work on these changes and comment back here.

**Comment by adamsilverstein** [comment]
This is fixed/updated in https://github.com/WP-API/client-js/pull/99 and https://github.com/WP-API/client-js/pull/103
