### ISSUE TITLE
Works locally, NOT A FUNCTION remotely! Help!

### ISSUE THREAD

**Issue by wearevilla** [WP-API/client-js#88]
Help! 
I am using the client-js and making it a dependency for my custom script. Enqueuing everything properly.

It works fine locally, but when I deploy to my server, it spits out an error saying that whatever reference to this client-js is not a function... But strangely, only on the first page load. If I refresh, it works fine. This is crazy! 

I need to have this working for a project immediately and it's driving me nuts. There is barely any good documentation on any of this, so any help is extremely appreciated.

Thanks in advance!

**Comment by adamsilverstein** [comment]
@wearevilla 

Happy to try to help! Do you have a test URL where I can see the failed load? can you provide a code snippet shoeing how you are enqueueing the script and using it in your script?

When you get the error, are you seeing it in the debugger console, your server error log or somewhere else? can you give the _exact_ error message you are seeing, and possibly a screen shot.

**Comment by wearevilla** [comment]
@adamsilverstein Hey! Thanks for the quick response! Currently the site I was trying this client at is here: http://clients.wearevilla.com/2dm.it

Unfortunately, it is for a client so, to preserve time, I just skipped using the js-client here and used new backbone collections. The whole site is actually powered using the wp-api, with a traditional php fallback for search engines and no-javascript users. 

I can assure you though, I enqueue properly and list dependencies properly in my functions file. I will try playing around with the js client again on another project and hope that problem does not occur again...

Thanks!

**Comment by adamsilverstein** [comment]
@wearevilla  ok, thanks for trying the library. that looks like a pretty cool project! anyway, please let me know if you have some code to share using the api that isn't working or want some help getting started. 

closing this issue for now; please reopen or open a new one if you have an update.
