### ISSUE TITLE
_.contains is not a function

### ISSUE THREAD

**Issue by pdme** [WP-API/client-js#89]
the method contains was removed in Lodash v4, and replaces by _.includes

https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings

**Comment by kadamwhite** [comment]
Contains is still valid in Underscore, which I believe is still what ships with WP Core. `_.includes` should be valid in either though, so I'd be in favor of making the switch to satisfy those who tend to replace underscore with lodash.

**Comment by adamsilverstein** [comment]
@pdme Thanks for pointing this out, and @kadamwhite thanks for the `includes` suggestion. This will afford the best compatibility between underscore and lodash. 

I prepared branch(https://github.com/WP-API/client-js/compare/fixes/includes-not-contains?expand=1) with the changes.

Unfortunately, it looks like the Underscore version bundled with Core only aliases `include`; newer versions also alias `includes` and we are working on upgrading Underscore for core (see https://core.trac.wordpress.org/ticket/34350). I'm going to hold off on merging this change until WordPress core upgrades; in the mean time you will need to add an alias yourself to avoid the error.

**Comment by adamsilverstein** [comment]
An update that we did merge upgraded backbone/underscore, however I'm hesitant to change as this would break compatibility with WordPress 4.4 which otherwise works fine with the library. Holding off on this change until we get to 4.6 or 4.7.  For now lodash users will have to add a line of code to map `contains` to `includes`

**Comment by kadamwhite** [comment]
Should that shim be defined locally?
```js
if ( typeof _.includes !== 'function' && typeof _.contains === 'function' ) {
  _.includes = _.contains;
}
```
(may not work, just spitballin')

**Comment by adamsilverstein** [comment]
Good suggestion @kadamwhite - very forward thinking! That would make the library work with 4.4, 4.5 and lodash. I will add and test. Thanks!

**Comment by adamsilverstein** [comment]
@pdme I added a shim and changed to using _.includes in https://github.com/WP-API/client-js/pull/101 so the library should work with lodash now.
