### ISSUE TITLE
PostMeta missing from wp.api.models

### ISSUE THREAD

**Issue by pdme** [WP-API/client-js#96]
There seem to be some endpoints missing, that are mentioned in the documentation, e.g. wp.api.models.PostsMeta, or wp.api.collections.Meta.

Have these been removed?

Any other way to manipulate post meta data?

**Comment by pdme** [comment]
Sorry, didn't have latest version installed.

**Comment by pdme** [comment]
reopening. 

I'm running the latest versions of both the rest-api plugin (2.0-beta12) and client-js, and endpoints like wp.api.models.PostMeta are missing.

any thoughts?

**Comment by danielbachhuber** [comment]
> Have these been removed?

Yes, they were removed in beta12. You'll need to install the meta endpoints plugin https://github.com/WP-API/wp-api-meta-endpoints

**Comment by pdme** [comment]
ah, that explains. thanks!

**Comment by adamsilverstein** [comment]
@pdme once you add the additional endpoint plugin the models/collections should reflect whats available. if you see any additional issues, please open a new issue. Thanks.

**Comment by praveenaj** [comment]
Following @danielbachhuber's advise I have WP REST API - Meta Endpoints installed but still I don't get meta objects. `wp.api.collections.PagesMeta`, `wp.api.collections.PostsMeta`, `wp.api.models.PagesMeta` and `wp.api.models.PostsMeta` are undefined.
